version: '3.7'

services:
  httprint:
    container_name: httprint
    build: .
    ports:
      - 8080:7777
    volumes:
      - ./httprint/queue:/httprint/queue
      - ./httprint/ppd:/httprint/ppd
